#!/bin/sh

if [ -z "$1" ]
  then
    echo "No argument supplied, go to https://github.com/github/gitignore/ for a list."
fi

curl https://raw.githubusercontent.com/github/gitignore/master/$1.gitignore -o ".gitignore"